version: '2'

volumes:
  harvest-activemq:
  harvest-pgsql:

services:
  activemq:
    image: rmohr/activemq:5.14.5-alpine
    env_file: .env
    ports: 
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    volumes:
      - "harvest-activemq:${ACTIVEMQ_DATA}"

  postgresql:
    image: postgres:10.1-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - harvest-pgsql:/var/lib/postgresql/data


